# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  request-ubuntuCRLF:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/6.0.0/hurl_6.0.0_amd64.deb
         sudo dpkg -i hurl_6.0.0_amd64.deb
         sudo apt install -y dos2unix
         unix2dos -n multistring-formrequest.hurl crlf.hurl
         hurl --variable host=https://httpbin.org/post --very-verbose --test crlf.hurl
         
  request-ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
         curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/6.0.0/hurl_6.0.0_amd64.deb
         sudo dpkg -i hurl_6.0.0_amd64.deb
         hurl --variable host=https://httpbin.org/post --very-verbose --test multistring-formrequest.hurl

  request-mappingservice:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
         docker run -d -p 8095:8095 --name mapping4docker ghcr.io/kit-data-manager/mapping-service:latest
         sleep 30
         curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/6.0.0/hurl_6.0.0_amd64.deb
         sudo dpkg -i hurl_6.0.0_amd64.deb
         hurl --variable host=http://localhost:8095/api/v1/mappingAdministration/ --very-verbose --test multistring-formrequest.hurl
         docker logs mapping4docker
